void print_alphabet(void);
void print_alphabet_x10(void);
int _putchar(char);
int _islower(int c);
int print_sign(int n);
int _isalpha(char);
int _abs(int);
int print_last_digit(int);
void jack_bauer();
void times_table(void);
int add(int, int);
void print_to_98(int);
void print_times_table(int);
void natural(void);
void fibonnaci50(void);
void fibonnaci_sum_even(void);
void fibonnaci98(void);
